export const formulaMapping: Record<string, string> = {
  'Target vs Delivered': 'Delivered ÷ Target',
  'Connection Requests': 'Count sent',
  'Acceptance Rate': '(Accepted ÷ Sent) × 100',
  'New Conversations': 'Count of replies',
  'Positive Response': '(Positive ÷ Replies) × 100',
  'Time to Response': 'Avg time from reply → response\n\nDetailed: (In Reply (Lead) – Adjacent Out Response (SDR)) averaged per convo, then per campaign',
  'Speed to Meeting': 'Avg time from positive → booked\n\nDetailed: meeting_booked_at – first_reply_at',
  'Meetings/Source': 'Meetings Booked ÷ Connections sent (by source)',
  'Show-Up Rate': '(Attended ÷ Booked) × 100',
  'Qualified Meetings': '(Qualified ÷ Attended) × 100',
  'SALs': 'Count approved by client',
  'Response SLA': 'On-time ÷ Total replies',
  'Lead Delivery SLA': 'Delivered ÷ Target',
  'Follow-Up SLA': 'Followed-up ÷ Positives',
  'Meeting Booking SLA': 'Avg hours from positive → booked',
  'Lead Refresh SLA': 'Avg restock time',
  'Feedback Logging SLA': 'Logged within 24h ÷ Total meetings',
  'Lead Burn Rate': 'Total Connections sent ÷ Days',
  'Days Until Depletion': 'Remaining ÷ Previous day Lead Burn Rate',
  'Campaigns at Risk': 'Count of campaigns with Days Until Depletion <72h',
  'Follow-Up Completion': 'Follow-ups ÷ Positives',
  'Recovery Rate': 'Rebooked ÷ Missed',
  'Error Rate': 'Errors ÷ Actions',
  'Experimentation Rate': 'Campaigns with A/B test ÷ Total',
  'Client On-Track': 'Binary (1 if all hit, else 0) or Weighted (≥0.8 composite score)\n\n**Criteria:** Delivery ≥90%, SLA ≥90%, Show-up ≥60%, Qualified ≥80%',
  'Campaign On-Track': 'Binary (1 if all hit, else 0) or Weighted (≥0.8 composite score)\n\n**Criteria (per campaign):** Delivery ≥90%, SLA ≥90%, Show-up ≥60%, Qualified ≥80%',

};