export const senders = [
  {
    _id: "1",
    name: "Sarah Chen",
    avatar: "https://i.pravatar.cc/40?img=1",
    status: "Active",
    statusCount: 28,
    company: "Acme corp",
    campaigns: 14,
    linkedin: "https://linkedin.com",
    campaignList: [
      "Lead Gen Q1",
      "Outbound Hiring",
      "SaaS Expansion",
      "Cold Outreach A",
    ],
    performance: {
      sent: 145,
       accepted: "32.2%",
      reply: "12.5%",
      interested: "14.5%",
    },
  },
  {
    _id: "2",
    name: "Sarah Chen",
    avatar: "https://i.pravatar.cc/40?img=2",
    status: "Less Active",
    statusCount: 8,
    company: "Hitashi",
    campaigns: 10,
    linkedin: "https://linkedin.com",
    campaignList: [
      "Lead Gen Q1",
      "Outbound Hiring",
      "SaaS Expansion",
      "Cold Outreach A",
    ],
    performance: {
      sent: 145,
     accepted: "32.2%",
      reply: "12.5%",
      interested: "14.5%",
    },
  },
  {
    _id: "3",
    name: "Sarah Chen",
    avatar: "https://i.pravatar.cc/40?img=3",
    status: "Inactive",
    statusCount: 19,
    linkedin: "https://linkedin.com",
    company: "HarshiTech",
    campaigns: 9,
    campaignList: [
      "Lead Gen Q1",
      "Outbound Hiring",
      "SaaS Expansion",
      "Cold Outreach A",
    ],
    performance: {
      sent: 145,
      accepted: "32.2%",
      reply: "12.5%",
      interested: "14.5%",
    },
  },
];
